### ISSUE TITLE
正規化資料表，988  990列出現神秘黑洞

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#232]
ubuntu@ubuntu:~/itaigi/server-side/log$ cat celery-error-logfile.log | grep -v INFO |less

```
[2016-08-27 20:07:03,745: ERROR/MainProcess] Task 臺灣言語平臺.tasks.新文本自資
料庫加入sheet[56e5a309-0c1c-4eb4-a6d3-76c50cc9e9bc] raised unexpected: ServerNot
FoundError('Unable to find the server at www.googleapis.com',)
Traceback (most recent call last):
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/celery/
app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/celery/
app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/tasks.py", line 10, in 新文本自資料庫加入sheet
    正規化sheet表.文本加入sheet(平臺項目編號)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/正規化團隊模型.py", line 53, in 文本加入sheet
    資料表 = 正規化sheet.提著資料表()
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/正規化團隊模型.py", line 39, in 提著資料表
    return gspread.authorize(登入憑證).open_by_url(
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/gspread
/client.py", line 331, in authorize

   client.login()
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/gspread/client.py", line 101, in login
    self.auth.refresh(http)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/client.py", line 668, in refresh
    self._refresh(http.request)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/client.py", line 873, in _refresh
    self._do_refresh_request(http_request)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/client.py", line 905, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/httplib2/__init__.py", line 994, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at www.googleapis.com
```

**Comment by aweimeow** [comment]
這是 DNS 掛了還是網路掛了還是他們服務掛了 XDD

**Comment by sih4sing5hong5** [comment]
```
50923	匿名	莫耳	móo-oh	móo-oh	莫耳	móo-oh	móo-oh		liz	
										出現神祕黑洞！？
50926	匿名	遊戲	kián-muh	kián-muh	遊戲	kián-muh	kián-muh		liz	
										出現神祕黑洞！？
50928	匿名	OK繃	OK貼	óo-khé-tah	OK繃	OK貼	óo-khé-tah		liz	
```

**Comment by sih4sing5hong5** [comment]
```
>>> from 臺灣言語平臺.項目模型 import 平臺項目表
>>> for ho in range(50923,50929):
...   a=平臺項目表.objects.get(id=ho)
...   print(ho,a.外語,a.文本)
...   
... 
50923 None móo-oh｜móo-oh
50924 墨爾本 None
50925 None 莫耳
50926 None kián-muh｜kián-muh
50927 None 莫耳
50928 None OK貼

```

**Comment by sih4sing5hong5** [comment]
```
150095	Nelson Chhong-iū Tân	輕拂	搧	siàn	輕拂	搧	siàn		hiantong																		
										"神秘黑洞
"																	
150109	匿名	沒出息	不准出門																								
```

**Comment by sih4sing5hong5** [comment]
`celery`停矣，重開才閣重走

**Comment by sih4sing5hong5** [comment]
資料攏補起來矣
59025
![2017-01-24 10 03 57](https://cloud.githubusercontent.com/assets/5996555/22231221/15a5e338-e21d-11e6-8790-f5f02fb694f3.png)
50927
150096
150108
![2017-01-24 10 08 24](https://cloud.githubusercontent.com/assets/5996555/22231222/15a8bcb6-e21d-11e6-85dd-1b217ddd43c1.png)
