### ISSUE TITLE
燒燙燙無更新

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#400]
```
ubuntu@ubuntu:~/itaigi/server-side$ less log/celery-error-logfile.log 

[2017-03-27 08:44:09,881: ERROR/MainProcess] Task 臺灣言語平臺.tasks.半瞑自sheet
s掠轉資料庫[044facd0-d18e-46d0-b04d-d4957e9a0005] raised unexpected: MultipleObj
ectsReturned('get() returned more than one 來源表 -- it returned 6!',)
Traceback (most recent call last):
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/celery/
app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/tasks.py", line 16, in 半瞑自sheets掠轉資料庫
    正規化sheet表.全部整理到資料庫()
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/正規化團隊模型.py", line 29, in 全部整理到資料庫
    sheet資料.整理到資料庫()
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/正規化團隊模型.py", line 93, in 整理到資料庫
    正規化sheet表.正規化文本自sheet加轉資料庫(這筆資料)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/正規化團隊模型.py", line 148, in 正規化文本自sheet加轉資料庫
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/項目模型.py", line 133, in 對正規化sheet校對母語文本
    新文本項目 = cls._校對母語文本(文本項目編號, 新文本內容)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語平臺/項目模型.py", line 140, in _校對母語文本
    新文本 = 舊文本.校對做(cls._補預設欄位(內容, 舊文本.種類.種類))
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語資料庫/資料模型.py", line 427, in 校對做
    文本 = 文本表.加資料(文本內容)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語資料庫/資料模型.py", line 410, in 加資料
    文本._加基本內容而且儲存(內容)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語資料庫/資料模型.py", line 176, in _加基本內容而且儲存
    self.來源 = self._揣來源資料(內容['來源'], True)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語資料庫/資料模型.py", line 206, in _揣來源資料
    return 來源表.揣來源(來源物件)
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言
語資料庫/資料模型.py", line 81, in 揣來源
    return 選擇.get(屬性數量=len(來源屬性陣列))
  File "/home/ubuntu/itaigi/server-side/venv/lib/python3.4/site-packages/django/db/models/query.py", line 391, in get
    (self.model._meta.object_name, num)
臺灣言語資料庫.資料模型.MultipleObjectsReturned: get() returned more than one 來源表 -- it returned 6!

**Comment by sih4sing5hong5** [comment]
應該無問題矣
