### ISSUE TITLE
正規化表匯入用了CDE欄位還沒正規化的資料

### ISSUE THREAD

**Issue by thewayiam** [g0v/itaigi#72]
CDE：
![column_not_match](https://cloud.githubusercontent.com/assets/4479861/16176241/cca3aafe-363b-11e6-95e4-63cd71fdc17a.jpg)
改用FGH的欄位，編輯者沒有簽名的就不顯示
另外google doc的欄位改變（J欄：編輯者 -> 編輯者(簽名)）會影響到[這行](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/blob/d83a26797e6f0db19bbe0ea7861b4d7e9088762e/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E5%B9%B3%E8%87%BA/%E7%B6%AD%E8%AD%B7%E5%9C%98%E9%9A%8A%E6%A8%A1%E5%9E%8B.py#L94)程式，看要改程式還是人不要改欄位名字

現在的`維護團隊模型.py` ，重複執行`python manage.py 加sheet的json 臺語 itaigi-sui2.json https://docs.google.com/spreadsheets/d/1_sXX2CGJsfSUTg-r-RGc4ApU1fPUmuLc2DmUSy4y_Zk/edit#gid=0`後會有重複id問題，要加一個update/delete（編輯者沒簽名）功能嗎？
update:
阿我搞懂了，`python manage.py 整理全部sheet到資料庫`才會把sheet的資料存進資料庫

**Comment by sih4sing5hong5** [comment]
### （J欄：編輯者 -> 編輯者(簽名)）
我覺得直接改程式，liz們看得清楚比較重要

### sheet到資料庫
除了`python manage.py 整理全部sheet到資料庫`
我還有打算用[crontab](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5#%E5%B0%87%E8%B3%87%E6%96%99%E5%B0%8Dsheet%E5%8C%AF%E5%85%A5%E8%B3%87%E6%96%99%E5%BA%AB)，不過還要試看看能不能每天跑一次

@thewayiam 我把你加到``專案裡了
你現在架後端有遇到什麼狀況嗎？
[sheet相關的issue](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/issues?q=is%3Aissue+is%3Aopen+label%3A%E7%B7%A8%E8%BC%AF%E5%9C%98%E9%9A%8A)

**Comment by thewayiam** [comment]
有補充了一些在README https://github.com/g0v/itaigi/commit/b926471bb1acfdc71f8ddc7db0a6bc363aec71fb
再麻煩看看有沒有什麼不妥當

**Comment by thewayiam** [comment]
現在碰到一個問題找不出頭緒，我把[後端網址](https://github.com/g0v/itaigi/blob/4228b1edfb535110c147b4aed629777669d4dc8d/src/App/App.jsx#L13) 改成`http://localhost:8000`，可以成功搜尋詞條例如＂討厭＂
執行`python manage.py 整理全部sheet到資料庫` 後有看到google doc的變化，但是在前端網頁收尋結果還是看不到google doc的資料

**Comment by sih4sing5hong5** [comment]
前端網頁現在沒有顯示校對後的，只有顯示使用者打的
資料庫應該有變化

為了解決這個問題，
我想說用後端來篩選
不過這樣就會改到api，所以我兩邊都還沒上版本
後端裝新版本`pip install --upgrade https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/archive/master.zip`
前端用`itaigi`的`後端升級到0.1.0版`branch

如果我們測過沒問題，我兩邊就都update上去

**Comment by thewayiam** [comment]
在跑`echo 'from 佳怡表匯入資料庫 import 走 ; 走()' | python manage.py shell`時少了MOTHER_TONGUE：
```
>>> 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/chinchen/trunk/itaigi/server-side/佳怡表匯入資料庫.py", line 75, in 走
    外語平臺項目 = 平臺項目表.加外語資料(外語內容)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言語平臺/項目模型.py", line 103, in 加外語資料
    外語 = 外語表.加資料(cls._補預設欄位(內容))
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言語平臺/項目模型.py", line 203, in _補預設欄位
    '語言腔口': settings.MOTHER_TONGUE,
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/django/conf/__init__.py", line 56, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'MOTHER_TONGUE'
>>> 

```

**Comment by sih4sing5hong5** [comment]
歹勢，我`itaigi`的`後端升級到0.1.0版`branch更新了

**Comment by thewayiam** [comment]
佳怡表匯入資料庫可以了前端也成功顯示
但執行`python manage.py 顯示全部sheet狀態` 會出錯如下：
（有再次升級過`pip install --upgrade https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/archive/master.zip`，確定 oauth2client==2.2.0）
```
(venv)chinchen@chinchen-UX305LA:~/trunk/itaigi/server-side$ python manage.py 顯示全部sheet狀態Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言語平臺/management/commands/顯示全部sheet狀態.py", line 17, in handle
    資料表 = sheet資料.提著資料表()
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/臺灣言語平臺/正規化團隊模型.py", line 40, in 提著資料表
    return gspread.authorize(登入憑證).open_by_url(
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/gspread/client.py", line 331, in authorize
    client.login()
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/gspread/client.py", line 101, in login
    self.auth.refresh(http)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/client.py", line 668, in refresh
    self._refresh(http.request)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/client.py", line 873, in _refresh
    self._do_refresh_request(http_request)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/client.py", line 900, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/client.py", line 1611, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/service_account.py", line 396, in _generate_assertion
    key_id=self._private_key_id)
  File "/home/chinchen/trunk/itaigi/server-side/venv/lib/python3.4/site-packages/oauth2client/crypt.py", line 97, in make_signed_jwt
    signature = signer.sign(signing_input)
AttributeError: 'bytes' object has no attribute 'sign'
```

**Comment by sih4sing5hong5** [comment]
我文件漏勾了


### sheet設定權限給後端
1. google sheet右上角的share
2. `can edit`輸入`itaigi-sui2.json`裡的`client_email`

**Comment by thewayiam** [comment]
有加了但還是會吐錯誤，之前有成功執行過

**Comment by sih4sing5hong5** [comment]
那我研究一下XDD

**Comment by thewayiam** [comment]
發現如果改回oauth2client==1.5.2的 [SignedJwtAssertionCredentials](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/blob/0.0.7/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E5%B9%B3%E8%87%BA/%E7%B6%AD%E8%AD%B7%E5%9C%98%E9%9A%8A%E6%A8%A1%E5%9E%8B.py#L3) 就可以了，我也來看一下新版2.2.0怎麼使用

**Comment by sih4sing5hong5** [comment]
剛看扣，是我`ServiceAccountCredentials`的用法錯了

當初找的升級2.0.0資料
https://github.com/google/oauth2client/releases/tag/v2.0.0

**Comment by thewayiam** [comment]
好，我會發個PR到 tai5-uan5_gian5-gi2_phing5-tai5

**Comment by thewayiam** [comment]
我好像不小心把後端升級到0.1.0版branch merge 進master了Orz，要還原嗎？
我測了google doc裡的資料還是不會顯示在前端

**Comment by sih4sing5hong5** [comment]
merge進去沒關係呀
沒有人`npm run deploy`就好XDD

現在db的資料只有匯入資料的`新台語網站資料表20150320.xlsx`和大家試驗的的資料
如果只是要試驗後端程式正不正常
前端`src/App/App.jsx`裡面有`後端網址`的變數可以改來試local db

如果覺得初使資料不過多
也可以再寫程式匯入`Taihoa楊允言老師提供資料庫-推薦用字表外字.csv`等三個臺華辭典的檔案

**Comment by sih4sing5hong5** [comment]
```
應該是因為google doc流水號和我 local db的流水號並不一樣，我 local 的並沒有這些流水號
請問除了匯入資料，還需要哪些步驟才能有完整的詞條？
```
其實我有想過[這個問題](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/issues/74)
不知道流水號這問題要怎麼處理比較好，目前想到的方法：

1. 直接寫另外一個指令匯入，並改原本表的流水號
2. 直接寫另外一個指令匯入，並且把原本表的資料複製到新的sheet，並且放新的流水號
1. 直接寫另外一個指令匯入，並改照原本表的流水號匯入，不過會有流水號衝突的問題

**Comment by sih4sing5hong5** [comment]
現在要改
[新文本自資料庫加入sheet](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/blob/master/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E5%B9%B3%E8%87%BA/%E6%AD%A3%E8%A6%8F%E5%8C%96%E5%9C%98%E9%9A%8A%E6%A8%A1%E5%9E%8B.py#L81)和[正規化文本自sheet加轉資料庫](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/blob/master/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E5%B9%B3%E8%87%BA/%E6%AD%A3%E8%A6%8F%E5%8C%96%E5%9C%98%E9%9A%8A%E6%A8%A1%E5%9E%8B.py#L96)兩個方向
@thewayiam 可以幫忙改看看嗎？

**Comment by thewayiam** [comment]
賀，挖來，順誜瞭蓋db結構

**Comment by sih4sing5hong5** [comment]
很久以前整理的[陽春說明](http://sih4sing5hong5.github.io/tai5-uan5_gian5-gi2_tsu1-liau7-khoo3/%E8%B3%87%E6%96%99%E7%B5%90%E6%A7%8B.html)
有問題我盡量解決XDD

**Comment by sih4sing5hong5** [comment]
看完資料庫格式後，
再看[項目模型.py
](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/blob/master/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E5%B9%B3%E8%87%BA/%E9%A0%85%E7%9B%AE%E6%A8%A1%E5%9E%8B.py)和[關係模型.py](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_tsu1-liau7-khoo3/blob/master/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E8%B3%87%E6%96%99%E5%BA%AB/%E9%97%9C%E4%BF%82%E6%A8%A1%E5%9E%8B.py)

**Comment by sih4sing5hong5** [comment]
https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/pull/117 做好矣
